### ISSUE TITLE
`test_multipart_modify_origins` is failing on CentOS 8 (4.18.0-383) xfs

### ISSUE THREAD

**Issue by e-kov** [elastio/elastio-snap#159]
The test is failing with the error `mount: /tmp/elio-snap-mnt016: mount(2) system call failed: Cannot allocate memory.`

```
elastio-snap: 36f6a10
kernel: 4.18.0-383.el8.x86_64
filesystem: xfs
gcc: 8.5.0
bash: 4.4.20(1)-release
python: Python 3.6.8

test_destroy_active_incremental (test_destroy.TestDestroy) ... ok
test_destroy_active_snapshot (test_destroy.TestDestroy) ... ok
test_destroy_dormant_incremental (test_destroy.TestDestroy) ... ok
test_destroy_dormant_snapshot (test_destroy.TestDestroy) ... ok
test_destroy_nonexistent_device (test_destroy.TestDestroy) ... ok
test_destroy_unverified_incremental (test_destroy.TestDestroy) ... ok
test_destroy_unverified_snapshot (test_destroy.TestDestroy) ... ok
test_multipart_modify_origins (test_multipart.TestMultipart) ... mount: /tmp/elio-snap-mnt016: mount(2) system call failed: Cannot allocate memory.
ERROR
test_multipart_setup_volumes_same_disk (test_multipart.TestMultipart) ... ok
test_multipart_setup_volumes_write_last_after_destroy (test_multipart.TestMultipart) ... ok
test_setup_2_volumes (test_setup.TestSetup) ... ok
test_setup_already_tracked_volume (test_setup.TestSetup) ... ok
test_setup_cow_file_path_is_dir (test_setup.TestSetup) ... ok
test_setup_invalid_minor (test_setup.TestSetup) ... ok
test_setup_readonly_volume (test_setup.TestSetup) ... ok
test_setup_unmounted_volume (test_setup.TestSetup) ... ok
test_setup_volume (test_setup.TestSetup) ... ok
test_setup_volume_path_is_dir (test_setup.TestSetup) ... ok
test_modify_origin (test_snapshot.TestSnapshot) ... ok
test_next_available_minor (test_snapshot.TestSnapshot) ... ok
test_track_writes (test_snapshot.TestSnapshot) ... skipped 'Broken on XFS, due to ignored os.sync and due to #63.'
test_transition_active_incremental (test_transition_incremental.TestTransitionToIncremental) ... ok
test_transition_active_snapshot (test_transition_incremental.TestTransitionToIncremental) ... ok
test_transition_fs_sync_cow_full (test_transition_incremental.TestTransitionToIncremental) ... ok
test_transition_mod_sync_cow_full (test_transition_incremental.TestTransitionToIncremental) ... skipped 'Kernel flushed before module'
test_transition_nonexistent_snapshot (test_transition_incremental.TestTransitionToIncremental) ... ok

======================================================================
ERROR: test_multipart_modify_origins (test_multipart.TestMultipart)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/elastio/elastio-snap/tests/test_multipart.py", line 101, in test_multipart_modify_origins
    util.mount(self.snap_devices[i], self.snap_mounts[i], opts)
  File "/home/elastio/elastio-snap/tests/util.py", line 20, in mount
    subprocess.check_call(cmd, timeout=10)
  File "/usr/lib64/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['mount', '/dev/elastio-snap16', '/tmp/elio-snap-mnt016', '-o', 'nouuid,norecovery,ro']' returned non-zero exit status 32.

----------------------------------------------------------------------
Ran 26 tests in 7.867s

FAILED (errors=1, skipped=2)
Error: Process completed with exit code 1.
```
dmesg: [dmesg_centos8.log](https://github.com/elastio/elastio-snap/files/9355104/dmesg_centos8.log)

**NOTE!** The test doesn't fail on CentOS 8 with the next Linux kernel version `4.18.0-394`.

**Comment by skypodolsky** [comment]
@e-kov checked in `4.18.0-408.el8.x86_64`, no issues were observed. It seems like a small kernel problem in that particular patch version. Should we close it?

**Comment by e-kov** [comment]
@skypodolsky well
4.18.0-383 - broken,
4.18.0-394 - ok,
4.18.0-408 - ok.
Two versions in a row the bug is not reproduced.
I'm closing it now.
