### ISSUE TITLE
Some test_destroy* tests randomly fail

### ISSUE THREAD

**Issue by skypodolsky** [elastio/elastio-snap#168]
###### Details:

Subtask of #166 

This is a very rare event, which was seen only once on Ubuntu 20.04 (ext2, RAID, amd64):

```
elastio-snap: d63df65
kernel: 5.15.0-46-generic
filesystem: ext2
gcc: 9.4.0-1ubuntu1~20.04.1)
bash: 5.0.17(1)-release
python: Python 3.8.10

test_destroy_active_incremental (test_destroy.TestDestroy) ... ok
test_destroy_active_snapshot (test_destroy.TestDestroy) ... FAIL
test_destroy_dormant_incremental (test_destroy.TestDestroy) ... FAIL
test_destroy_dormant_snapshot (test_destroy.TestDestroy) ... FAIL
test_destroy_nonexistent_device (test_destroy.TestDestroy) ... FAIL
test_destroy_unverified_incremental (test_destroy.TestDestroy) ... ok
test_destroy_unverified_snapshot (test_destroy.TestDestroy) ... ok
test_multipart_modify_origins (test_multipart.TestMultipart) ... skipped 'Multipart testcase does not support LVM/raid devices creation'
test_multipart_setup_volumes_same_disk (test_multipart.TestMultipart) ... skipped 'Multipart testcase does not support LVM/raid devices creation'
test_multipart_setup_volumes_write_last_after_destroy (test_multipart.TestMultipart) ... skipped 'Multipart testcase does not support LVM/raid devices creation'
test_setup_2_volumes (test_setup.TestSetup) ... ok
test_setup_already_tracked_volume (test_setup.TestSetup) ... ok
test_setup_cow_file_path_is_dir (test_setup.TestSetup) ... ok
test_setup_invalid_minor (test_setup.TestSetup) ... ok
test_setup_readonly_volume (test_setup.TestSetup) ... ok
test_setup_unmounted_volume (test_setup.TestSetup) ... ok
test_setup_volume (test_setup.TestSetup) ... ok
test_setup_volume_path_is_dir (test_setup.TestSetup) ... ok
test_modify_origin (test_snapshot.TestSnapshot) ... ok
test_next_available_minor (test_snapshot.TestSnapshot) ... ok
test_track_writes (test_snapshot.TestSnapshot) ... ok
test_transition_active_incremental (test_transition_incremental.TestTransitionToIncremental) ... ok
test_transition_active_snapshot (test_transition_incremental.TestTransitionToIncremental) ... ok
test_transition_fs_sync_cow_full (test_transition_incremental.TestTransitionToIncremental) ... ok
test_transition_mod_sync_cow_full (test_transition_incremental.TestTransitionToIncremental) ... skipped 'Kernel flushed before module'
test_transition_nonexistent_snapshot (test_transition_incremental.TestTransitionToIncremental) ... ok

======================================================================
FAIL: test_destroy_active_snapshot (test_destroy.TestDestroy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/elastio/elastio-snap/tests/test_destroy.py", line [31](https://github.com/elastio/elastio-snap/actions/runs/3098834488/jobs/5018143097#step:26:32), in test_destroy_active_snapshot
    self.assertEqual(elastio_snap.destroy(self.minor), 0)
AssertionError: 16 != 0

======================================================================
FAIL: test_destroy_dormant_incremental (test_destroy.TestDestroy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/elastio/elastio-snap/tests/test_destroy.py", line 55, in test_destroy_dormant_incremental
    self.assertEqual(elastio_snap.setup(self.minor, self.device, self.cow_full_path), 0)
AssertionError: 16 != 0

======================================================================
FAIL: test_destroy_dormant_snapshot (test_destroy.TestDestroy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/elastio/elastio-snap/tests/test_destroy.py", line 44, in test_destroy_dormant_snapshot
    self.assertEqual(elastio_snap.setup(self.minor, self.device, self.cow_full_path), 0)
AssertionError: 16 != 0

======================================================================
FAIL: test_destroy_nonexistent_device (test_destroy.TestDestroy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/elastio/elastio-snap/tests/test_destroy.py", line 26, in test_destroy_nonexistent_device
    self.assertEqual(elastio_snap.destroy(self.minor), errno.ENOENT)
AssertionError: 0 != 2
```

**Comment by e-kov** [comment]
@skypodolsky could it be that `test_destroy_*` tests need the same adjustment of the `mount/umount` cleanups as you did in PR https://github.com/elastio/elastio-snap/pull/215 for the fix of https://github.com/elastio/elastio-snap/issues/202 ?

**Comment by Sir-Alex-L** [comment]
Not sure if related. Tried building on clean install Debian 11.6 and ran the tests.

First run of tests. I downloaded the release v0.12.2 directly.

```
./elio-test.sh: line 89: git: command not found
elastio-snap:
kernel: 5.10.0-22-amd64
filesystem: ext4
gcc: 10.2.1-6)
bash: 5.1.4(1)-release
python: Python 3.9.2

test_destroy_active_incremental (test_destroy.TestDestroy) ... ok
test_destroy_active_snapshot (test_destroy.TestDestroy) ... ok
test_destroy_dormant_incremental (test_destroy.TestDestroy) ... ok
test_destroy_dormant_snapshot (test_destroy.TestDestroy) ... ok
test_destroy_nonexistent_device (test_destroy.TestDestroy) ... ok
test_destroy_unverified_incremental (test_destroy.TestDestroy) ... ok
test_destroy_unverified_snapshot (test_destroy.TestDestroy) ... ok
ERROR
ERROR
ERROR
ERROR
ERROR

======================================================================
ERROR: setUpClass (test_multipart.TestMultipart)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/debian/elastio-snap-0.12.2/tests/devicetestcase_multipart.py", line 50, in setUpClass
    cls.device = util.loop_create(cls.backing_store, cls.part_count)
  File "/home/debian/elastio-snap-0.12.2/tests/util.py", line 106, in loop_create
    partition(loopdev, part_count)
  File "/home/debian/elastio-snap-0.12.2/tests/util.py", line 94, in partition
    subprocess.check_call(cmd, timeout=30)
  File "/usr/lib/python3.9/subprocess.py", line 368, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.9/subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'parted'

======================================================================
ERROR: setUpClass (test_reload.TestReload)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/debian/elastio-snap-0.12.2/tests/devicetestcase.py", line 29, in setUpClass
    cls.kmod.load(debug=1)
  File "/home/debian/elastio-snap-0.12.2/tests/kmod.py", line 29, in load
    subprocess.check_call(
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['insmod', '../src/elastio-snap.ko', 'debug=1']' returned non-                                                                           zero exit status 1.

======================================================================
ERROR: setUpClass (test_setup.TestSetup)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/debian/elastio-snap-0.12.2/tests/devicetestcase.py", line 29, in setUpClass
    cls.kmod.load(debug=1)
  File "/home/debian/elastio-snap-0.12.2/tests/kmod.py", line 29, in load
    subprocess.check_call(
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['insmod', '../src/elastio-snap.ko', 'debug=1']' returned non-                                                                           zero exit status 1.

======================================================================
ERROR: setUpClass (test_snapshot.TestSnapshot)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/debian/elastio-snap-0.12.2/tests/devicetestcase.py", line 29, in setUpClass
    cls.kmod.load(debug=1)
  File "/home/debian/elastio-snap-0.12.2/tests/kmod.py", line 29, in load
    subprocess.check_call(
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['insmod', '../src/elastio-snap.ko', 'debug=1']' returned non-                                                                           zero exit status 1.

======================================================================
ERROR: setUpClass (test_transition_incremental.TestTransitionToIncremental)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/debian/elastio-snap-0.12.2/tests/devicetestcase.py", line 29, in setUpClass
    cls.kmod.load(debug=1)
  File "/home/debian/elastio-snap-0.12.2/tests/kmod.py", line 29, in load
    subprocess.check_call(
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['insmod', '../src/elastio-snap.ko', 'debug=1']' returned non-                                                                           zero exit status 1.

----------------------------------------------------------------------
Ran 7 tests in 4.251s

FAILED (errors=5)
```

Second run, I cloned it via git

```
debian@debian:~/git-elastio/elastio-snap/tests$ sudo ./elio-test.sh

elastio-snap: dda3e37
kernel: 5.10.0-22-amd64
filesystem: ext4
gcc: 10.2.1-6)
bash: 5.1.4(1)-release
python: Python 3.9.2

ERROR
ERROR
ERROR
ERROR
ERROR
ERROR

======================================================================
ERROR: setUpClass (test_destroy.TestDestroy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/debian/git-elastio/elastio-snap/tests/devicetestcase.py", line 29, in setUpClass
    cls.kmod.load(debug=1)
  File "/home/debian/git-elastio/elastio-snap/tests/kmod.py", line 29, in load
    subprocess.check_call(
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['insmod', '../src/elastio-snap.ko', 'debug=1']' returned non-zero exit status 1.

======================================================================
ERROR: setUpClass (test_multipart.TestMultipart)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/debian/git-elastio/elastio-snap/tests/devicetestcase_multipart.py", line 39, in setUpClass
    cls.kmod.load(debug=1)
  File "/home/debian/git-elastio/elastio-snap/tests/kmod.py", line 29, in load
    subprocess.check_call(
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['insmod', '../src/elastio-snap.ko', 'debug=1']' returned non-zero exit status 1.

======================================================================
ERROR: setUpClass (test_reload.TestReload)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/debian/git-elastio/elastio-snap/tests/devicetestcase.py", line 29, in setUpClass
    cls.kmod.load(debug=1)
  File "/home/debian/git-elastio/elastio-snap/tests/kmod.py", line 29, in load
    subprocess.check_call(
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['insmod', '../src/elastio-snap.ko', 'debug=1']' returned non-zero exit status 1.

======================================================================
ERROR: setUpClass (test_setup.TestSetup)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/debian/git-elastio/elastio-snap/tests/devicetestcase.py", line 29, in setUpClass
    cls.kmod.load(debug=1)
  File "/home/debian/git-elastio/elastio-snap/tests/kmod.py", line 29, in load
    subprocess.check_call(
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['insmod', '../src/elastio-snap.ko', 'debug=1']' returned non-zero exit status 1.

======================================================================
ERROR: setUpClass (test_snapshot.TestSnapshot)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/debian/git-elastio/elastio-snap/tests/devicetestcase.py", line 29, in setUpClass
    cls.kmod.load(debug=1)
  File "/home/debian/git-elastio/elastio-snap/tests/kmod.py", line 29, in load
    subprocess.check_call(
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['insmod', '../src/elastio-snap.ko', 'debug=1']' returned non-zero exit status 1.

======================================================================
ERROR: setUpClass (test_transition_incremental.TestTransitionToIncremental)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/debian/git-elastio/elastio-snap/tests/devicetestcase.py", line 29, in setUpClass
    cls.kmod.load(debug=1)
  File "/home/debian/git-elastio/elastio-snap/tests/kmod.py", line 29, in load
    subprocess.check_call(
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['insmod', '../src/elastio-snap.ko', 'debug=1']' returned non-zero exit status 1.

----------------------------------------------------------------------
Ran 0 tests in 0.046s

```

**Comment by e-kov** [comment]
@Sir-Alex-L thanks for your interest in using `elastio-snap`.

Better to use latest `master` instead of `v0.12.2` release. It has some known issues which were recently fixed in `master`. We have to re-create this latest release to point correct commits. @skypodolsky FYI.

> Not sure if related. Tried building on clean install Debian 11.6 and ran the tests.

It's not related.

> First run of tests. I downloaded the release v0.12.2 directly.

The 1st failure is related to the absence of `parted` utility on your machine. It's used to create partitions for the tests on a loopback device.
```
FileNotFoundError: [Errno 2] No such file or directory: 'parted'
```

> Second run, I cloned it via git

This time you had `elastio_snap` kernel module loaded before the 2nd tests start.
```
subprocess.CalledProcessError: Command '['insmod', '../src/elastio-snap.ko', 'debug=1']' returned non-zero exit status 1.
```
The module loads in `setup` and unloads in `teardown`. The module was remaining loaded after the previous failure. 
The resolution is to `sudo rmmod elastio_snap`.

**Comment by Sir-Alex-L** [comment]
> The 1st failure is related to the absence of `parted` utility on your machine. It's used to create partitions for the tests on a loopback device.
> 
> ```
> FileNotFoundError: [Errno 2] No such file or directory: 'parted'
> ```

Well I feel stupid, should have read the logs more closely.

Thanks! I hid my other comment.
