### ISSUE TITLE
Driver fails to unload

### ISSUE THREAD

**Issue by skypodolsky** [elastio/elastio-snap#169]
###### Details:

Subtask of #166 

This rare issue was seen a couple of times on Ubuntu 22.04:

```
elastio-snap: d63df65
kernel: 5.15.0-47-generic
filesystem: xfs
gcc: 11.2.0-19ubuntu1)
bash: 5.1.16(1)-release
python: Python 3.10.4

  Physical volume "/dev/loop3p1" successfully created.
  Physical volume "/dev/loop4p1" successfully created.
  Volume group "vg_mirror9" successfully created
  Rounding up size to full physical extent 232.00 MiB
  Logical volume "lv_mirror9" created.
test_destroy_active_incremental (test_destroy.TestDestroy) ... ok
test_destroy_active_snapshot (test_destroy.TestDestroy) ... ok
test_destroy_dormant_incremental (test_destroy.TestDestroy) ... ok
test_destroy_dormant_snapshot (test_destroy.TestDestroy) ... ok
test_destroy_nonexistent_device (test_destroy.TestDestroy) ... ok
test_destroy_unverified_incremental (test_destroy.TestDestroy) ... ok
test_destroy_unverified_snapshot (test_destroy.TestDestroy) ... ok
  Logical volume "lv_mirror9" successfully removed
  Volume group "vg_mirror9" successfully removed
test_multipart_modify_origins (test_multipart.TestMultipart) ... skipped 'Multipart testcase does not support LVM/raid devices creation'
test_multipart_setup_volumes_same_disk (test_multipart.TestMultipart) ... skipped 'Multipart testcase does not support LVM/raid devices creation'
test_multipart_setup_volumes_write_last_after_destroy (test_multipart.TestMultipart) ... skipped 'Multipart testcase does not support LVM/raid devices creation'
  Physical volume "/dev/loop4p1" successfully created.
  Physical volume "/dev/loop7p1" successfully created.
  Volume group "vg_mirror0" successfully created
  Rounding up size to full physical extent 232.00 MiB
  Logical volume "lv_mirror0" created.
test_setup_2_volumes (test_setup.TestSetup) ... ok
test_setup_already_tracked_volume (test_setup.TestSetup) ... ok
test_setup_cow_file_path_is_dir (test_setup.TestSetup) ... ok
test_setup_invalid_minor (test_setup.TestSetup) ... ok
test_setup_readonly_volume (test_setup.TestSetup) ... ok
test_setup_unmounted_volume (test_setup.TestSetup) ... ok
test_setup_volume (test_setup.TestSetup) ... ok
test_setup_volume_path_is_dir (test_setup.TestSetup) ... ok
  Logical volume "lv_mirror0" successfully removed
  Volume group "vg_mirror0" successfully removed
ERROR
ERROR

======================================================================
Couldn't unload the driver
Couldn't unload the driver
Couldn't unload the driver
ERROR: setUpClass (test_snapshot.TestSnapshot)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/elastio/elastio-snap/tests/devicetestcase.py", line 27, in setUpClass
    cls.kmod.load(debug=1)
  File "/home/elastio/elastio-snap/tests/kmod.py", line 29, in load
    subprocess.check_call(
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['insmod', '../src/elastio-snap.ko', 'debug=1']' returned non-zero exit status 1.

======================================================================
ERROR: setUpClass (test_transition_incremental.TestTransitionToIncremental)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/elastio/elastio-snap/tests/devicetestcase.py", line 27, in setUpClass
    cls.kmod.load(debug=1)
  File "/home/elastio/elastio-snap/tests/kmod.py", line 29, in load
    subprocess.check_call(
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['insmod', '../src/elastio-snap.ko', 'debug=1']' returned non-zero exit status 1.
```

**Comment by NDVas** [comment]
Retested using 
Elastio CLI: 0.21.27 (0cd8962 2022-10-14 02:15:08)
Account-level stack: 2022-10-11
Region-level stack: 0.21.24

Not reproduced. Tried xfs, ext4, ext3 file systems, ran a lot of block backups and checked the status of drivers after.
