### ISSUE TITLE
Tests on LVM devices are failing on kernel 5.19.0

### ISSUE THREAD

**Issue by e-kov** [elastio/elastio-snap#171]
OS: Pop!OS 22.04
Linux kernel: 5.19.0-76051900-generic

Test output:
```
sudo ./elio-test.sh -l

elastio-snap: 14a57c1
kernel: 5.19.0-76051900-generic
filesystem: ext4
gcc: 11.2.0-19ubuntu1)
bash: 5.1.16(1)-release
python: Python 3.10.6

  Physical volume "/dev/loop0p1" successfully created.
  Physical volume "/dev/loop1p1" successfully created.
  Volume group "vg_mirror3" successfully created
  Rounding up size to full physical extent 232.00 MiB
  Logical volume "lv_mirror3" created.
ERROR
test_multipart_modify_origins (test_multipart.TestMultipart) ... skipped 'Multipart testcase does not support LVM/raid devices creation'
test_multipart_setup_volumes_same_disk (test_multipart.TestMultipart) ... skipped 'Multipart testcase does not support LVM/raid devices creation'
test_multipart_setup_volumes_write_last_after_destroy (test_multipart.TestMultipart) ... skipped 'Multipart testcase does not support LVM/raid devices creation'
ERROR
ERROR
ERROR

======================================================================
ERROR: setUpClass (test_destroy.TestDestroy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/elastio/elastio-snap/tests/devicetestcase.py", line 55, in setUpClass
    util.mkfs(cls.device, cls.fs)
  File "/home/elastio/elastio-snap/tests/util.py", line 122, in mkfs
    subprocess.check_call(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, timeout=120)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['mkfs.ext4', '-F', '/dev/dm-5']' died with <Signals.SIGKILL: 9>.

======================================================================
ERROR: setUpClass (test_setup.TestSetup)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/elastio/elastio-snap/tests/devicetestcase.py", line 27, in setUpClass
    cls.kmod.load(debug=1)
  File "/home/elastio/elastio-snap/tests/kmod.py", line 27, in load
    subprocess.check_call(
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['insmod', '../src/elastio-snap.ko', 'debug=1']' returned non-zero exit status 1.

======================================================================
ERROR: setUpClass (test_snapshot.TestSnapshot)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/elastio/elastio-snap/tests/devicetestcase.py", line 27, in setUpClass
    cls.kmod.load(debug=1)
  File "/home/elastio/elastio-snap/tests/kmod.py", line 27, in load
    subprocess.check_call(
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['insmod', '../src/elastio-snap.ko', 'debug=1']' returned non-zero exit status 1.

======================================================================
ERROR: setUpClass (test_transition_incremental.TestTransitionToIncremental)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/elastio/elastio-snap/tests/devicetestcase.py", line 27, in setUpClass
    cls.kmod.load(debug=1)
  File "/home/elastio/elastio-snap/tests/kmod.py", line 27, in load
    subprocess.check_call(
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['insmod', '../src/elastio-snap.ko', 'debug=1']' returned non-zero exit status 1.

----------------------------------------------------------------------
Ran 3 tests in 3.932s

FAILED (errors=4, skipped=3)
```
dmesg: [dmesg.log](https://github.com/elastio/elastio-snap/files/9659434/dmesg.log)

**Comment by e-kov** [comment]
The same VM has obtained new kernel after `apt update/upgrade`. It was `5.19.0-76051900-generic` and now it is `6.0.12-76060006-generic`.
The issue is not reproducible now.

Output of `sudo ./elio-test.sh -l`: 
```
elastio-snap: 7612806
kernel: 6.0.12-76060006-generic
filesystem: ext4
gcc: 11.3.0-1ubuntu1~22.04)
bash: 5.1.16(1)-release
python: Python 3.10.6

  Physical volume "/dev/loop0p1" successfully created.
  Physical volume "/dev/loop1p1" successfully created.
  Volume group "vg_mirror7" successfully created
  Rounding up size to full physical extent 232.00 MiB
  Logical volume "lv_mirror7" created.
test_destroy_active_incremental (test_destroy.TestDestroy) ... ok
test_destroy_active_snapshot (test_destroy.TestDestroy) ... ok
test_destroy_dormant_incremental (test_destroy.TestDestroy) ... ok
test_destroy_dormant_snapshot (test_destroy.TestDestroy) ... ok
test_destroy_nonexistent_device (test_destroy.TestDestroy) ... ok
test_destroy_unverified_incremental (test_destroy.TestDestroy) ... ok
test_destroy_unverified_snapshot (test_destroy.TestDestroy) ... ok
  Logical volume "lv_mirror7" successfully removed
  Volume group "vg_mirror7" successfully removed
test_multipart_modify_origins (test_multipart.TestMultipart) ... skipped 'Multipart testcase does not support LVM/raid devices creation'
test_multipart_setup_volumes_same_disk (test_multipart.TestMultipart) ... skipped 'Multipart testcase does not support LVM/raid devices creation'
test_multipart_setup_volumes_write_last_after_destroy (test_multipart.TestMultipart) ... skipped 'Multipart testcase does not support LVM/raid devices creation'
  Physical volume "/dev/loop0p1" successfully created.
  Physical volume "/dev/loop1p1" successfully created.
  Volume group "vg_mirror7" successfully created
  Rounding up size to full physical extent 232.00 MiB
  Logical volume "lv_mirror7" created.
test_reload_inc_device_no_exists (test_reload.TestReload) ... ok
test_reload_inc_invalid_minor (test_reload.TestReload) ... ok
test_reload_inc_volume_path_is_dir (test_reload.TestReload) ... ok
test_reload_snap_device_no_exists (test_reload.TestReload) ... ok
test_reload_snap_invalid_minor (test_reload.TestReload) ... ok
test_reload_snap_volume_path_is_dir (test_reload.TestReload) ... ok
test_reload_unverified_incremental (test_reload.TestReload) ... ok
test_reload_unverified_snapshot (test_reload.TestReload) ... ok
test_reload_verified_inc (test_reload.TestReload) ... ok
test_reload_verified_snapshot (test_reload.TestReload) ... ok
  Logical volume "lv_mirror7" successfully removed
  Volume group "vg_mirror7" successfully removed
  Physical volume "/dev/loop0p1" successfully created.
  Physical volume "/dev/loop1p1" successfully created.
  Volume group "vg_mirror16" successfully created
  Rounding up size to full physical extent 232.00 MiB
  Logical volume "lv_mirror16" created.
test_setup_2_volumes (test_setup.TestSetup) ... ok
test_setup_already_tracked_volume (test_setup.TestSetup) ... ok
test_setup_cow_file_path_is_dir (test_setup.TestSetup) ... ok
test_setup_invalid_minor (test_setup.TestSetup) ... ok
test_setup_readonly_volume (test_setup.TestSetup) ... ok
test_setup_unmounted_volume (test_setup.TestSetup) ... ok
test_setup_volume (test_setup.TestSetup) ... ok
test_setup_volume_path_is_dir (test_setup.TestSetup) ... ok
  Logical volume "lv_mirror16" successfully removed
  Volume group "vg_mirror16" successfully removed
  Physical volume "/dev/loop0p1" successfully created.
  Physical volume "/dev/loop1p1" successfully created.
  Volume group "vg_mirror4" successfully created
  Rounding up size to full physical extent 232.00 MiB
  Logical volume "lv_mirror4" created.
test_modify_origin (test_snapshot.TestSnapshot) ... ok
test_next_available_minor (test_snapshot.TestSnapshot) ... ok
test_track_writes (test_snapshot.TestSnapshot) ... ok
  Logical volume "lv_mirror4" successfully removed
  Volume group "vg_mirror4" successfully removed
  Physical volume "/dev/loop0p1" successfully created.
  Physical volume "/dev/loop1p1" successfully created.
  Volume group "vg_mirror1" successfully created
  Rounding up size to full physical extent 232.00 MiB
  Logical volume "lv_mirror1" created.
test_transition_active_incremental (test_transition_incremental.TestTransitionToIncremental) ... ok
test_transition_active_snapshot (test_transition_incremental.TestTransitionToIncremental) ... ok
test_transition_fs_sync_cow_full (test_transition_incremental.TestTransitionToIncremental) ... ok
test_transition_mod_sync_cow_full (test_transition_incremental.TestTransitionToIncremental) ... ok
test_transition_nonexistent_snapshot (test_transition_incremental.TestTransitionToIncremental) ... ok
  Logical volume "lv_mirror1" successfully removed
  Volume group "vg_mirror1" successfully removed

----------------------------------------------------------------------
Ran 36 tests in 40.686s

OK (skipped=3)
```
[dmesg.log](https://github.com/elastio/elastio-snap/files/10387218/dmesg.log)

`5.19.0` is not LTS per https://www.kernel.org/category/releases.html and it's already EOLed per https://en.wikipedia.org/wiki/Linux_kernel_version_history.

Thus, no need to keep this issue open.
