### ISSUE TITLE
Tests are failing on the Debian 9 (kernel 4.9.0-13)

### ISSUE THREAD

**Issue by e-kov** [elastio/elastio-snap#50]
The tests are failing: https://github.com/elastio/elastio-snap/runs/1190012942?check_suite_focus=true#step:10:181
```
elastio-snap: 6bba25b
kernel: 4.9.0-13-amd64
gcc: 6.3.0-18+deb9u1)
bash: 4.4.12(1)-release
python: Python 3.5.3

test_destroy_active_incremental (test_destroy.TestDestroy) ... FAIL
test_destroy_active_snapshot (test_destroy.TestDestroy) ... FAIL
test_destroy_dormant_incremental (test_destroy.TestDestroy) ... skipped 'Broken since 4.17 (see #144)'
test_destroy_dormant_snapshot (test_destroy.TestDestroy) ... skipped 'Broken since 4.17 (see #144)'
test_destroy_nonexistent_device (test_destroy.TestDestroy) ... FAIL
test_destroy_unverified_incremental (test_destroy.TestDestroy) ... umount: /tmp/elastio-snap: target is busy
        (In some cases useful info about processes that
         use the device is found by lsof(8) or fuser(1).)
ERROR
test_destroy_unverified_snapshot (test_destroy.TestDestroy) ... umount: /tmp/elastio-snap: target is busy
        (In some cases useful info about processes that
         use the device is found by lsof(8) or fuser(1).)
umount: /tmp/elastio-snap: target is busy
        (In some cases useful info about processes that
         use the device is found by lsof(8) or fuser(1).)
ERROR
ERROR
ERROR
ERROR
ERROR

======================================================================
ERROR: test_destroy_unverified_incremental (test_destroy.TestDestroy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/elastio/elastio-snap/tests/test_destroy.py", line 81, in test_destroy_unverified_incremental
    util.unmount(self.mount)
  File "/home/elastio/elastio-snap/tests/util.py", line 23, in unmount
    subprocess.check_call(cmd, timeout=10)
  File "/usr/lib/python3.5/subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['umount', '/tmp/elastio-snap']' returned non-zero exit status 32

======================================================================
ERROR: test_destroy_unverified_snapshot (test_destroy.TestDestroy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/elastio/elastio-snap/tests/test_destroy.py", line 72, in test_destroy_unverified_snapshot
    util.unmount(self.mount)
  File "/home/elastio/elastio-snap/tests/util.py", line 23, in unmount
    subprocess.check_call(cmd, timeout=10)
  File "/usr/lib/python3.5/subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['umount', '/tmp/elastio-snap']' returned non-zero exit status 32

======================================================================
ERROR: tearDownClass (test_destroy.TestDestroy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/elastio/elastio-snap/tests/devicetestcase.py", line 34, in tearDownClass
    util.unmount(cls.mount)
  File "/home/elastio/elastio-snap/tests/util.py", line 23, in unmount
    subprocess.check_call(cmd, timeout=10)
  File "/usr/lib/python3.5/subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['umount', '/tmp/elastio-snap']' returned non-zero exit status 32

======================================================================
ERROR: setUpClass (test_setup.TestSetup)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/elastio/elastio-snap/tests/devicetestcase.py", line 24, in setUpClass
    cls.kmod.load(debug=1)
  File "/home/elastio/elastio-snap/tests/kmod.py", line 31, in load
    timeout=self.timeout)
  File "/usr/lib/python3.5/subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['insmod', '../src/elastio-snap.ko', 'debug=1']' returned non-zero exit status 1

======================================================================
ERROR: setUpClass (test_snapshot.TestSnapshot)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/elastio/elastio-snap/tests/devicetestcase.py", line 24, in setUpClass
    cls.kmod.load(debug=1)
  File "/home/elastio/elastio-snap/tests/kmod.py", line 31, in load
    timeout=self.timeout)
  File "/usr/lib/python3.5/subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['insmod', '../src/elastio-snap.ko', 'debug=1']' returned non-zero exit status 1

======================================================================
ERROR: setUpClass (test_transition_incremental.TestTransitionToIncremental)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/elastio/elastio-snap/tests/devicetestcase.py", line 24, in setUpClass
    cls.kmod.load(debug=1)
  File "/home/elastio/elastio-snap/tests/kmod.py", line 31, in load
    timeout=self.timeout)
  File "/usr/lib/python3.5/subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['insmod', '../src/elastio-snap.ko', 'debug=1']' returned non-zero exit status 1

======================================================================
FAIL: test_destroy_active_incremental (test_destroy.TestDestroy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/elastio/elastio-snap/tests/test_destroy.py", line 40, in test_destroy_active_incremental
    self.assertEqual(elastio_snap.transition_to_incremental(self.minor), 0)
AssertionError: 5 != 0

======================================================================
FAIL: test_destroy_active_snapshot (test_destroy.TestDestroy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/elastio/elastio-snap/tests/test_destroy.py", line 32, in test_destroy_active_snapshot
    self.assertEqual(elastio_snap.setup(self.minor, self.device, self.cow_full_path), 0)
AssertionError: 16 != 0

======================================================================
FAIL: test_destroy_nonexistent_device (test_destroy.TestDestroy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/elastio/elastio-snap/tests/test_destroy.py", line 29, in test_destroy_nonexistent_device
    self.assertEqual(elastio_snap.destroy(self.minor), errno.ENOENT)
AssertionError: 0 != 2

----------------------------------------------------------------------
Ran 7 tests in 1.150s

FAILED (failures=3, errors=6, skipped=2)
Error: Process completed with exit code 1.

```
Or even hanging: https://github.com/elastio/elastio-snap/runs/1189842448?check_suite_focus=true#step:10:184
```
elastio-snap: fedecce
kernel: 4.9.0-13-amd64
gcc: 6.3.0-18+deb9u1)
bash: 4.4.12(1)-release
python: Python 3.5.3
test_destroy_active_incremental (test_destroy.TestDestroy) ... FAIL

test_destroy_active_snapshot (test_destroy.TestDestroy) ... FAIL
test_destroy_dormant_incremental (test_destroy.TestDestroy) ... skipped 'Broken since 4.17 (see #144)'
test_destroy_dormant_snapshot (test_destroy.TestDestroy) ... skipped 'Broken since 4.17 (see #144)'
Error: The operation was canceled.
```

**Comment by e-kov** [comment]
The issue happens after the first `freeze` - `thaw` operation during the tests. And it's seems to be an issue in the loop device driver. I tried to use different `losetup` options to workaround this issue, such as switch on and off direct IO, set start offset (to not r/w first blocks of the loop device), set size limit, tried to use different file systems (ext2 - ext4) and different mount options.
As result, the error is various, starting from ` blk_update_request: I/O error, dev loop0, sector 2` on the ext4 and ending with the segfault on the ext2.
An example of the error from dmesg:
```
[  +0.000016] blk_update_request: I/O error, dev loop0, sector 2
[  +0.000247] blk_update_request: I/O error, dev loop0, sector 2
[  +0.000210] Buffer I/O error on dev loop0, logical block 1, lost sync page write
```
The more detailed log is attached: [dmesg.log](https://github.com/elastio/elastio-snap/files/5329097/dmesg.log)
