### ISSUE TITLE
tests on a loop device cannot unmount it due to kernel panic with kernel 5.8

### ISSUE THREAD

**Issue by e-kov** [elastio/elastio-snap#71]
The tests output is hang on the `test_destroy_unverified_incremental (test_destroy.TestDestroy)`, interrupted by Ctrl+C:
```[elastio@fedora33-amd64-build tests]$ sudo ./elio-test.sh 
Python module CFFI is not installed. Installing it...
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Requirement already satisfied: cffi in /usr/local/lib64/python3.9/site-packages (1.14.4)
Requirement already satisfied: pycparser in /usr/local/lib/python3.9/site-packages (from cffi) (2.20)

elastio-snap: 6b5d915
kernel: 5.8.15-301.fc33.x86_64
gcc: 10.2.1
bash: 5.0.17(1)-release
python: Python 3.9.0

test_destroy_active_incremental (test_destroy.TestDestroy) ... ok
test_destroy_active_snapshot (test_destroy.TestDestroy) ... ok
test_destroy_dormant_incremental (test_destroy.TestDestroy) ... skipped 'Broken since 4.17 (see #144)'
test_destroy_dormant_snapshot (test_destroy.TestDestroy) ... skipped 'Broken since 4.17 (see #144)'
test_destroy_nonexistent_device (test_destroy.TestDestroy) ... ok
test_destroy_unverified_incremental (test_destroy.TestDestroy) ... ^CTraceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib64/python3.9/unittest/__main__.py", line 18, in <module>
    main(module=None)
  File "/usr/lib64/python3.9/unittest/main.py", line 101, in __init__
    self.runTests()
  File "/usr/lib64/python3.9/unittest/main.py", line 271, in runTests
    self.result = testRunner.run(self.test)
  File "/usr/lib64/python3.9/unittest/runner.py", line 176, in run
    test(result)
  File "/usr/lib64/python3.9/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib64/python3.9/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/lib64/python3.9/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib64/python3.9/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/lib64/python3.9/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib64/python3.9/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/lib64/python3.9/unittest/case.py", line 653, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib64/python3.9/unittest/case.py", line 593, in run
    self._callTestMethod(testMethod)
  File "/usr/lib64/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/home/elastio/elastio-snap/tests/test_destroy.py", line 78, in test_destroy_unverified_incremental
    util.unmount(self.mount)
  File "/home/elastio/elastio-snap/tests/util.py", line 23, in unmount
    subprocess.check_call(cmd, timeout=10)
  File "/usr/lib64/python3.9/subprocess.py", line 368, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib64/python3.9/subprocess.py", line 351, in call
    return p.wait(timeout=timeout)
  File "/usr/lib64/python3.9/subprocess.py", line 1185, in wait
    return self._wait(timeout=timeout)
  File "/usr/lib64/python3.9/subprocess.py", line 1909, in _wait
    time.sleep(delay)
KeyboardInterrupt
```
Tail of the dmesg:
```
[  +0,035524] elastio-snap: ioctl command received: -1605353208
[  +0,000007] elastio-snap: received elastio-snap info ioctl - 12
[  +0,000001] elastio-snap: device specified does not exist: -2
[  +0,000001] elastio-snap: error during reconfigure ioctl handler: -2
[  +0,000001] elastio-snap: minor range = 23 - 0
[  +0,002920] elastio-snap: ioctl command received: 1074020612
[  +0,000002] elastio-snap: received destroy ioctl - 12
[  +0,000002] elastio-snap: device specified does not exist: -2
[  +0,000001] elastio-snap: error during destroy ioctl handler: -2
[  +0,000002] elastio-snap: minor range = 23 - 0
[  +0,023255] ------------[ cut here ]------------
[  +0,000009] percpu ref (blk_queue_usage_counter_release) <= 0 (-149) after switching to atomic
[  +0,000058] WARNING: CPU: 2 PID: 0 at lib/percpu-refcount.c:161 percpu_ref_switch_to_atomic_rcu+0x12f/0x140
[  +0,000001] Modules linked in: loop elastio_snap(OE) fuse xt_conntrack xt_MASQUERADE nf_conntrack_netlink nft_counter xt_addrtype nft_compat br_netfilter bridge stp llc nft_masq nft_fib_inet nft_fib_ipv4 nft_fib_ipv6 nft_fib nft_reject_inet nf_reject_ipv4 nf_reject_ipv6 nft_reject nft_ct nft_chain_nat nf_nat nf_conntrack nf_defrag_ipv6 nf_defrag_ipv4 rfkill ip_set overlay nf_tables nfnetlink intel_rapl_msr intel_rapl_common kvm_intel kvm irqbypass crct10dif_pclmul crc32_pclmul crc32c_intel ghash_clmulni_intel cirrus rapl drm_kms_helper cec virtio_net net_failover failover virtio_balloon joydev i2c_piix4 drm zram ip_tables virtio_blk ata_generic serio_raw qemu_fw_cfg pata_acpi
[  +0,000043] CPU: 2 PID: 0 Comm: swapper/2 Tainted: G           OE     5.8.15-301.fc33.x86_64 #1
[  +0,000002] Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS 1.13.0-1ubuntu1.1 04/01/2014
[  +0,000005] RIP: 0010:percpu_ref_switch_to_atomic_rcu+0x12f/0x140
[  +0,000004] Code: eb 99 80 3d b4 ef 62 01 00 0f 85 4d ff ff ff 48 8b 55 d8 48 8b 75 e8 48 c7 c7 a0 f9 3f a7 c6 05 98 ef 62 01 01 e8 f7 72 ae ff <0f> 0b e9 2b ff ff ff 0f 0b eb a2 cc cc cc cc cc cc 8d 8c 16 ef be
[  +0,000002] RSP: 0018:ffffb70a000e4ef0 EFLAGS: 00010286
[  +0,000002] RAX: 0000000000000052 RBX: 7fffffffffffff6a RCX: 0000000000000000
[  +0,000001] RDX: 0000000000000052 RSI: ffffffffa83f6452 RDI: 0000000000000246
[  +0,000002] RBP: ffff97258d101688 R08: 0000000a9e96093b R09: 0000000000000052
[  +0,000001] R10: 0000000080000002 R11: ffffffffa83f6437 R12: 00003fe44803e438
[  +0,000002] R13: 0000000000000000 R14: ffff9725b6e6cd80 R15: ffff9725b7d2b0d0
[  +0,000002] FS:  0000000000000000(0000) GS:ffff9725b7d00000(0000) knlGS:0000000000000000
[  +0,000029] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  +0,000002] CR2: 00007f996e9ab9b0 CR3: 0000000215308003 CR4: 0000000000360ee0
[  +0,000008] Call Trace:
[  +0,000018]  <IRQ>
[  +0,000008]  rcu_do_batch+0x197/0x3e0
[  +0,000013]  rcu_core+0x189/0x2e0
[  +0,000006]  ? sched_clock+0x5/0x10
[  +0,000005]  __do_softirq+0xd9/0x2c4
[  +0,000010]  asm_call_irq_on_stack+0xf/0x20
[  +0,000007]  </IRQ>
[  +0,000002]  do_softirq_own_stack+0x37/0x40
[  +0,000004]  irq_exit_rcu+0xc2/0x100
[  +0,000006]  sysvec_apic_timer_interrupt+0x34/0x80
[  +0,000017]  asm_sysvec_apic_timer_interrupt+0x12/0x20
[  +0,000003] RIP: 0010:native_safe_halt+0xe/0x10
[  +0,000003] Code: 02 20 48 8b 00 a8 08 75 c4 e9 7b ff ff ff cc cc cc cc cc cc cc cc cc cc cc cc cc cc e9 07 00 00 00 0f 00 2d d6 59 49 00 fb f4 <c3> 90 e9 07 00 00 00 0f 00 2d c6 59 49 00 f4 c3 cc cc 0f 1f 44 00
[  +0,000002] RSP: 0018:ffffb70a0007bed0 EFLAGS: 00000246
[  +0,000002] RAX: ffffffffa6b73480 RBX: 0000000000000002 RCX: 0000000000000000
[  +0,000001] RDX: 0000000000000002 RSI: ffffb70a0007bea0 RDI: 0000000a9de98b85
[  +0,000001] RBP: 0000000000000002 R08: 0000000000000001 R09: ffff9725b1597a00
[  +0,000002] R10: 00000000000003a1 R11: 0000000000000000 R12: 0000000000000000
[  +0,000001] R13: 0000000000000000 R14: 0000000000000000 R15: 0000000000000000
[  +0,000003]  ? __sched_text_end+0x3/0x3
[  +0,000004]  default_idle+0x1a/0x140
[  +0,000003]  do_idle+0x1f3/0x2a0
[  +0,000003]  ? arch_cpu_idle_exit+0x40/0x40
[  +0,000003]  cpu_startup_entry+0x19/0x20
[  +0,000004]  start_secondary+0x144/0x170
[  +0,000008]  secondary_startup_64+0xb6/0xc0
[  +0,000004] ---[ end trace e4e6c8608ee7fe2b ]---
```

Full dmesg: [dmesg.log](https://github.com/elastio/elastio-snap/files/5996611/dmesg.log)

**Comment by anelson** [comment]
@e-kov what are the implications of this issue?  I thought you worked around this as part of the work in #72.
